# 扫描包
scan.package=cn.jackiegu.spring.study
# 模板文件路径
template=template
# AOP配置
pointcut=cn.jackiegu.spring.study.service.impl.UserServiceImpl.save
aspect.class=cn.hutool.aop.aspects.TimeIntervalAspect
aspect.before=before
aspect.after=after
